name: level1

on:
    push:
        branches: ["master","main"]


jobs:
    hello:
     env:
        BUILD_MODE: "DEBUG"
     runs-on: ubuntu-latest
     steps:

        - run: echo "OS is ${{runner.os}}"
        